import Link from "next/link";
import type { getTravellerDashboard } from "@/services/traveller-dashboard";

type Dashboard = Awaited<ReturnType<typeof getTravellerDashboard>>;

function date(value: Date | null) {
  return value ? new Intl.DateTimeFormat("en-KE", { day: "numeric", month: "short", year: "numeric" }).format(value) : "Dates to be arranged";
}

function RequestList({ title, requests }: { title: string; requests: Dashboard["requestsByStatus"]["pending"] }) {
  return <section className="dashboard-section"><div className="dashboard-heading"><h2>{title}</h2><span>{requests.length}</span></div>{requests.length ? <div className="dashboard-list">{requests.map((request) => <article key={request.id} className="dashboard-card"><div><p className="card-type">{request.status}</p><h3>{request.listing.title}</h3><p className="muted">{request.listing.location} · {date(request.startDate)}</p></div><p className="dashboard-guests">{request.guests ? `${request.guests} guest${request.guests === 1 ? "" : "s"}` : "Guest count to be arranged"}</p></article>)}</div> : <p className="dashboard-empty">No {title.toLowerCase()} yet.</p>}</section>;
}

export function TravellerDashboard({ data }: { data: Dashboard }) {
  const travellerName = data.traveller.name?.trim().split(" ")[0] || data.traveller.email || "Traveller";

  return <main className="dashboard-page"><nav className="dashboard-nav container"><Link href="/" className="brand"><span>SC</span>SafariConnect</Link><Link href="/" className="text-link">Explore Kenya</Link></nav><div className="container dashboard-content"><p className="eyebrow">YOUR TRAVEL SPACE</p><h1>Karibu, {travellerName}.</h1><p className="dashboard-intro">Keep your requests, upcoming journeys, saved places, and conversations together.</p><section className="dashboard-section"><div className="dashboard-heading"><h2>Upcoming trips</h2><span>{data.trips.length}</span></div>{data.trips.length ? <div className="dashboard-list">{data.trips.map((trip) => <article key={trip.id} className="dashboard-card"><div><p className="card-type">Confirmed journey</p><h3>{trip.bookingRequest.listing.title}</h3><p className="muted">{trip.bookingRequest.listing.location} · {date(trip.startDate)}</p></div></article>)}</div> : <p className="dashboard-empty">Accepted booking requests will appear here as trips.</p>}</section><div className="dashboard-request-grid"><RequestList title="Pending requests" requests={data.requestsByStatus.pending} /><RequestList title="Confirmed requests" requests={data.requestsByStatus.accepted} /><RequestList title="Declined requests" requests={data.requestsByStatus.declined} /><RequestList title="Cancelled requests" requests={data.requestsByStatus.cancelled} /></div><section className="dashboard-section"><div className="dashboard-heading"><h2>Saved places</h2><span>{data.wishlist.length}</span></div>{data.wishlist.length ? <div className="dashboard-list">{data.wishlist.map((item) => <article key={item.id} className="dashboard-card"><div><p className="card-type">Saved</p><h3>{item.listing.title}</h3><p className="muted">{item.listing.location}</p></div><strong>From {item.listing.currency} {item.listing.priceFrom.toString()}</strong></article>)}</div> : <p className="dashboard-empty">Save a place you love while exploring Kenya.</p>}</section><section className="dashboard-section"><div className="dashboard-heading"><h2>Messages</h2><span>{data.messages.length}</span></div>{data.messages.length ? <div className="dashboard-list">{data.messages.map((message) => <article key={message.id} className="dashboard-card"><div><p className="card-type">{message.listing?.title ?? "Booking conversation"}</p><h3>{message.sender.name}</h3><p className="muted">{message.content}</p></div><time className="dashboard-time">{date(message.createdAt)}</time></article>)}</div> : <p className="dashboard-empty">Your conversations with hosts will appear here.</p>}</section></div></main>;
}
